# Generated by Django 2.2.10 on 2020-02-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = []

	operations = [
		migrations.CreateModel(
			name="Article",
			fields=[
				("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("title", models.CharField(max_length=120)),
				("author", models.CharField(max_length=120)),
				("created", models.DateTimeField(auto_now_add=True)),
				("revised", models.DateTimeField(auto_now=True)),
				("content", models.TextField()),
				("summary", models.TextField()),
				("publish", models.BooleanField()),
			],
		),
	]
